namespace UnityEngine.Rendering.PostProcessing
{
	[ExecuteAlways]
	[AddComponentMenu("Rendering/Post-process Debug", 1002)]
	public sealed class PostProcessDebug : MonoBehaviour
	{
		public PostProcessLayer postProcessLayer;

		private PostProcessLayer m_PreviousPostProcessLayer;

		public bool lightMeter;

		public bool histogram;

		public bool waveform;

		public bool vectorscope;

		public DebugOverlay debugOverlay;

		private Camera m_CurrentCamera;

		private CommandBuffer m_CmdAfterEverything;

		private void OnEnable()
		{
		}

		private void OnDisable()
		{
		}

		private void Update()
		{
		}

		private void Reset()
		{
		}

		private void UpdateStates()
		{
		}

		private void OnPostRender()
		{
		}

		private void OnGUI()
		{
		}

		private void DrawMonitor(ref Rect rect, Monitor monitor, bool enabled)
		{
		}
	}
}
